export const ENEMY_TYPES = {
      BASIC: {
        src: "basicEnemy.png",
        hp: 100,
        damage: 5,
        type: "basic",
        speed: 0.25, // from 0.150 * 1.5
        baseSpeed: 0.25, // from 0.150 * 1.5
        regen: 0,
        canRegen: false,
        isArmored: false,
      },
      STEALTH: {
        src: "stealth.png",
        hp: 50,
        damage: 10,
        type: "stealth",
        speed: 0.25, // from 0.150 * 1.5
        baseSpeed: 0.25, // from 0.150 * 1.5
        regen: 0,
        canRegen: false,
        isArmored: false,
      },
      TANK: {
        src: "tank.png",
        hp: 350,
        damage: 5,
        type: "basic",
        speed: 0.2, // from 0.125 * 1.5
        baseSpeed: 0.2, // from 0.125 * 1.5
        regen: 0,
        canRegen: false,
        isArmored: false,
      },
      SPEEDY: {
        src: "speedy.png",
        hp: 40,
        damage: 35,
        type: "speedy",
        speed: 1.6, // from 1.0 * 1.5
        baseSpeed: 1.6, // from 1.0 * 1.5
        regen: 0,
        canRegen: false,
        isArmored: false,
      },
      STEALTHYTANK: {
        src: "stealthyTank.png",
        hp: 250,
        damage: 20,
        type: "stealth",
        speed: 0.2, // from 0.125 * 1.5
        baseSpeed: 0.2, // from 0.125 * 1.5
        regen: 0,
        canRegen: false,
        isArmored: false,
      },
      STEALTHYSPEEDY: {
        src: "stealthySpeedy.png",
        hp: 50,
        damage: 50,
        type: "stealth",
        speed: 1.6, // from 1.0 * 1.5
        baseSpeed: 1.6, // from 1.0 * 1.5
        regen: 0,
        canRegen: false,
        isArmored: false,
      },
      REGENTANK: {
        src: "regenTank.png",
        hp: 400,
        damage: 50,
        type: "regentank",
        speed: 0.2, // from 0.125 * 1.5
        baseSpeed: 0.2, // from 0.125 * 1.5
        regen: 75,
        canRegen: true,
        isArmored: false,
      },
      SPEEDYREGENTANK: {
        src: "regenTank.png",
        hp: 600,
        damage: 50,
        type: "speedyregentank",
        speed: 0.375, // from 0.2 * 1.5
        baseSpeed: 0.375, // from 0.2 * 1.5
        regen: 125,
        canRegen: true,
        isArmored: false,
      },
      BOSS: {
        src: "boss.png",
        hp: 50000,
        damage: 1000,
        type: "boss",
        speed: 0.16,
        baseSpeed: 0.16,
        regen: 1000,
        canRegen: true,
        isArmored: false,
        stunReduction: 0.8,
        slowReduction: 0.8,
      },
      ULTRATANKS: {
        src: "ultraTank.png",
        hp: 1750,
        damage: 1000,
        type: "ultratank",
        speed: 0.17,
        baseSpeed: 0.17,
        regen: 0,
        canRegen: false,
        isArmored: false,
      },
      ARMOREDBASIC: {
        src: "armoredbasicEnemy.png",
        hp: 125,
        damage: 30,
        type: "armoredbasic",
        speed: 0.225,
        baseSpeed: 0.225,
        regen: 0,
        canRegen: false,
        isArmored: true,
      },
      ARMOREDTANK: {
        src: "armoredtank.png",
        hp: 400,
        damage: 400,
        type: "armoredtank",
        speed: 0.2,
        baseSpeed: 0.2,
        regen: 0,
        canRegen: false,
        isArmored: true,
      },
      ARMOREDULTRATANK: {
        src: "armoredultraTank.png",
        hp: 2000,
        damage: 1000,
        type: "armoredultratank",
        speed: 0.225,
        baseSpeed: 0.225,
        regen: 0,
        canRegen: false,
        isArmored: true,
      },
      ARMOREDSPEEDYMEGATANK: {
        src: "armoredspeedyMegaTank.png",
        hp: 3500,
        damage: 1000,
        type: "armoredultratank",
        speed: 0.6,
        baseSpeed: 0.6,
        regen: 0,
        canRegen: false,
        isArmored: true,
      },
      SPEEDYMEGATANK: {
        src: "speedyMegaTank.png",
        hp: 3000,
        damage: 1000,
        type: "armoredultratank",
        speed: 0.6,
        baseSpeed: 0.6,
        regen: 0,
        canRegen: false,
        isArmored: true,
      },
      MEGABOSS: {
        src: "megaBoss.png",
        hp: 125000,
        damage: 1000,
        type: "boss",
        speed: 0.225,
        baseSpeed: 0.225,
        regen: 5000,
        canRegen: true,
        isArmored: false,
        stunReduction: 0.4,
        slowReduction: 0.4,
      },
      ULTRABOSS: {
        src: "boss.png",
        hp: 500000,
        damage: 1000,
        type: "boss",
        speed: 0.325,
        baseSpeed: 0.325,
        regen: 50000,
        canRegen: true,
        isArmored: false,
        stunReduction: 0.2,
        slowReduction: 0.2,
      },
      SPAWNER: {
        src: "boss.png",
        hp: 2000,
        damage: 100,
        type: "spawner",
        speed: 0.2,
        baseSpeed: 0.2,
        regen: 0,
        canRegen: false,
        isArmored: false,
        canSpawn: true,
        spawnType: "SPEEDYMEGATANK",
      },
      GIGASPAWNER: {
        src: "boss.png",
        hp: 5000,
        damage: 100,
        type: "spawner",
        speed: 0.2,
        baseSpeed: 0.2,
        regen: 0,
        canRegen: false,
        isArmored: false,
        canSpawn: true,
        spawnType: "SPEEDYGIGATANK",
      },
      MEGABOSSSPAWNER: {
        src: "boss.png",
        hp: 25000,
        damage: 100,
        type: "spawner",
        speed: 0.2,
        baseSpeed: 0.2,
        regen: 0,
        canRegen: false,
        isArmored: false,
        canSpawn: true,
        spawnType: "MEGABOSS",
      },
      SPEEDYGIGATANK: {
        src: "speedyGigaTank.png",
        hp: 10000,
        damage: 1000,
        type: "speedygigatank",
        speed: 0.5,
        baseSpeed: 0.5,
        regen: 0,
        canRegen: false,
        isArmored: true,
      },
    }